
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/quick_tug.pnct \
    $(DIST)/quick_tug.scene \


$(DIST)/quick_tug.scene : quick_tug.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "quick_tug.blend:Main" "$(DIST)/quick_tug.scene"

$(DIST)/quick_tug.pnct : quick_tug.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "quick_tug.blend:Main" "$(DIST)/quick_tug.pnct" 